// IMDb title tt0485301 episode stills, verified by exact season/episode number.
const episodeImages = {
  S01E01: { imdbEpisodeId: 'tt0772650', imdbTitle: 'Everything Changes', url: 'https://m.media-amazon.com/images/M/MV5BOTQ2NjgxODM2OV5BMl5BanBnXkFtZTgwMzIwNTUyMjE@._V1_.jpg' },
  S01E02: { imdbEpisodeId: 'tt0852919', imdbTitle: 'Day One', url: 'https://m.media-amazon.com/images/M/MV5BNzBhMmNmYjAtYTRmYi00NmVlLWJiZWYtODQ0NjRhNzBjYTQ1XkEyXkFqcGc@._V1_.jpg' },
  S01E03: { imdbEpisodeId: 'tt0852920', imdbTitle: 'Ghost Machine', url: 'https://m.media-amazon.com/images/M/MV5BM2Q4ZDhhMDQtYjI0OS00Y2ZmLTg4OWYtNDI2YTljMDlmOThkXkEyXkFqcGc@._V1_.jpg' },
  S01E04: { imdbEpisodeId: 'tt0852921', imdbTitle: 'Cyberwoman', url: 'https://m.media-amazon.com/images/M/MV5BYjJmYTRmNTAtN2Q3YS00ZDg2LWFjZWItYjk0YzM1YzYzNDZkXkEyXkFqcGc@._V1_.jpg' },
  S01E05: { imdbEpisodeId: 'tt0881831', imdbTitle: 'Small Worlds', url: 'https://m.media-amazon.com/images/M/MV5BODY2YWYwMjAtYzgwZC00YTk3LWExZTQtMTI5MjM0ZDUwZmNhXkEyXkFqcGc@._V1_.jpg' },
  S01E06: { imdbEpisodeId: 'tt0887098', imdbTitle: 'Countrycide', url: 'https://m.media-amazon.com/images/M/MV5BY2E5ZjIxMGQtZGIzZC00NzY5LWI4ZTUtZTViNjY1ZGEzNTlmXkEyXkFqcGc@._V1_.jpg' },
  S01E07: { imdbEpisodeId: 'tt0852918', imdbTitle: 'Greeks Bearing Gifts', url: 'https://m.media-amazon.com/images/M/MV5BMmMxMjEzMDItZjA1Zi00MTE3LTkwMTEtOTQ2OGUxMDRmY2E4XkEyXkFqcGc@._V1_.jpg' },
  S01E08: { imdbEpisodeId: 'tt0887099', imdbTitle: 'They Keep Killing Suzie', url: 'https://m.media-amazon.com/images/M/MV5BNWRmOTAxNWQtNDdhZC00MWI0LThjM2MtNTE3ZGU5ZTcwZjZhXkEyXkFqcGc@._V1_.jpg' },
  S01E09: { imdbEpisodeId: 'tt0898059', imdbTitle: 'Random Shoes', url: 'https://m.media-amazon.com/images/M/MV5BZjM3MDMzMDEtNjhjMS00YWRkLWEzYzQtYWYzMDZmZGEwYzU1XkEyXkFqcGc@._V1_.jpg' },
  S01E10: { imdbEpisodeId: 'tt0898831', imdbTitle: 'Out of Time', url: 'https://m.media-amazon.com/images/M/MV5BOTFjZTNkMzYtYmQwNC00MzNiLWI0MWUtOWFlODdmNDI5MjgwXkEyXkFqcGc@._V1_.jpg' },
  S01E11: { imdbEpisodeId: 'tt0918317', imdbTitle: 'Combat', url: 'https://m.media-amazon.com/images/M/MV5BNzdjOWI0ZGYtYTkwYS00ZDhiLWJiNTEtMzAxMWUwMmY0ZmE1XkEyXkFqcGc@._V1_.jpg' },
  S01E12: { imdbEpisodeId: 'tt0898830', imdbTitle: 'Captain Jack Harkness', url: 'https://m.media-amazon.com/images/M/MV5BMjEzODc2NjU3Ml5BMl5BanBnXkFtZTgwNjUzMzYyMjE@._V1_.jpg' },
  S01E13: { imdbEpisodeId: 'tt0912349', imdbTitle: 'End of Days', url: 'https://m.media-amazon.com/images/M/MV5BNmRlMzkzZmYtZTE3My00NThjLThiYzUtNmI2MzVmNmY4YmZlXkEyXkFqcGc@._V1_.jpg' },
  S02E01: { imdbEpisodeId: 'tt1153680', imdbTitle: 'Kiss Kiss, Bang Bang', url: 'https://m.media-amazon.com/images/M/MV5BOWY4ZThmYWMtNWI0OC00NzZjLWI5ZGUtMTQwZWVkMzJlZGJkXkEyXkFqcGc@._V1_.jpg' },
  S02E02: { imdbEpisodeId: 'tt1160003', imdbTitle: 'Sleeper', url: 'https://m.media-amazon.com/images/M/MV5BOTE1ZDIxODktMjAyZS00ODM1LWI3NDQtMDMxYzI4OGYyY2MwXkEyXkFqcGc@._V1_.jpg' },
  S02E03: { imdbEpisodeId: 'tt1160284', imdbTitle: 'To the Last Man', url: 'https://m.media-amazon.com/images/M/MV5BOGFmMjE0ODItZjY4Yy00ODgxLWFkODctOTQxMzc1ODI4ZjMwXkEyXkFqcGc@._V1_.jpg' },
  S02E04: { imdbEpisodeId: 'tt1160285', imdbTitle: 'Meat', url: 'https://m.media-amazon.com/images/M/MV5BYzgzMzI2OGMtNDQzZC00OWMyLWJlNWUtM2NkM2IzOWJlYzBkXkEyXkFqcGc@._V1_.jpg' },
  S02E05: { imdbEpisodeId: 'tt1160001', imdbTitle: 'Adam', url: 'https://m.media-amazon.com/images/M/MV5BOGI0ZjEyNzktYjA0Yy00YWEzLTkwNjktMWVmYjAzODY1ZDYwXkEyXkFqcGc@._V1_.jpg' },
  S02E06: { imdbEpisodeId: 'tt1160002', imdbTitle: 'Reset', url: 'https://m.media-amazon.com/images/M/MV5BMThhNTMxNWUtYjJkYS00NGU0LWE1NmItZDZhMWM0NjMyNmNiXkEyXkFqcGc@._V1_.jpg' },
  S02E07: { imdbEpisodeId: 'tt1186346', imdbTitle: 'Dead Man Walking', url: 'https://m.media-amazon.com/images/M/MV5BZTYzZTkwZTQtZmRiOC00ZjU5LWI3YjEtM2ZiMzgyOGI3MmQ1XkEyXkFqcGc@._V1_.jpg' },
  S02E08: { imdbEpisodeId: 'tt1186345', imdbTitle: 'A Day in the Death', url: 'https://m.media-amazon.com/images/M/MV5BYjRiODgxMzEtMWJhMC00MGU2LWI0MjMtMTJhNzcwYjc1NGI4XkEyXkFqcGc@._V1_.jpg' },
  S02E09: { imdbEpisodeId: 'tt1186347', imdbTitle: 'Something Borrowed', url: 'https://m.media-amazon.com/images/M/MV5BNDZhMmZkMGQtODdlZi00Mzk3LWI2MDgtMzkwNDIyNzBkYjdhXkEyXkFqcGc@._V1_.jpg' },
  S02E10: { imdbEpisodeId: 'tt1190503', imdbTitle: 'From Out of the Rain', url: 'https://m.media-amazon.com/images/M/MV5BNmIzMjVkOGMtYzZhYS00OTUyLTlhMDgtYjRjODYxYmMyYjhjXkEyXkFqcGc@._V1_.jpg' },
  S02E11: { imdbEpisodeId: 'tt1190500', imdbTitle: 'Adrift', url: 'https://m.media-amazon.com/images/M/MV5BZTg1MWIyZjEtODNkNi00Mjg3LWJkOWItNTQ3ZjI1OTAwNDE2XkEyXkFqcGc@._V1_.jpg' },
  S02E12: { imdbEpisodeId: 'tt1190502', imdbTitle: 'Fragments', url: 'https://m.media-amazon.com/images/M/MV5BYjFkODkwNjYtM2FmMy00OTVhLWJkY2QtMDU1OTdmYjdkM2ViXkEyXkFqcGc@._V1_.jpg' },
  S02E13: { imdbEpisodeId: 'tt1190501', imdbTitle: 'Exit Wounds', url: 'https://m.media-amazon.com/images/M/MV5BNDM5Njg3OTg5NF5BMl5BanBnXkFtZTgwNDQ1MzYyMjE@._V1_.jpg' },
  S03E01: { imdbEpisodeId: 'tt1288549', imdbTitle: 'Children of Earth: Day One', url: 'https://m.media-amazon.com/images/M/MV5BMTQ2NDk4NjYzOV5BMl5BanBnXkFtZTgwNTczNzUyMjE@._V1_.jpg' },
  S03E02: { imdbEpisodeId: 'tt1287276', imdbTitle: 'Children of Earth: Day Two', url: 'https://m.media-amazon.com/images/M/MV5BZmIyOWY4ZTgtMzAzNy00ODQyLThhODItZjIwMGI4NmZiZjBmXkEyXkFqcGc@._V1_.jpg' },
  S03E03: { imdbEpisodeId: 'tt1287277', imdbTitle: 'Children of Earth: Day Three', url: 'https://m.media-amazon.com/images/M/MV5BMWQ4NzE2YTAtYjE2YS00NWY3LWE4NjgtMmQ0MmM4ZDAwODE4XkEyXkFqcGc@._V1_.jpg' },
  S03E04: { imdbEpisodeId: 'tt1287278', imdbTitle: 'Children of Earth: Day Four', url: 'https://m.media-amazon.com/images/M/MV5BMzQ0M2Q5MTQtZTNhYi00NzhkLWJhYjAtZDM1MmQyNjIxMDA2XkEyXkFqcGc@._V1_.jpg' },
  S03E05: { imdbEpisodeId: 'tt1287279', imdbTitle: 'Children of Earth: Day Five', url: 'https://m.media-amazon.com/images/M/MV5BMTg4Mzg0Mjc4Ml5BMl5BanBnXkFtZTgwMzc0ODUyMjE@._V1_.jpg' },
  S04E01: { imdbEpisodeId: 'tt1798034', imdbTitle: 'Miracle Day: The New World', url: 'https://m.media-amazon.com/images/M/MV5BMTM3MDkyNzU0M15BMl5BanBnXkFtZTcwNzIwMTc4NQ@@._V1_.jpg' },
  S04E02: { imdbEpisodeId: 'tt1819351', imdbTitle: 'Miracle Day: Rendition', url: 'https://m.media-amazon.com/images/M/MV5BMjA2MzY1Nzg1N15BMl5BanBnXkFtZTgwOTYxMTYyMjE@._V1_.jpg' },
  S04E03: { imdbEpisodeId: 'tt1819350', imdbTitle: 'Miracle Day: Dead of Night', url: 'https://m.media-amazon.com/images/M/MV5BNDAwMzk1NTg0M15BMl5BanBnXkFtZTgwMzQxMTYyMjE@._V1_.jpg' },
  S04E04: { imdbEpisodeId: 'tt1819345', imdbTitle: 'Miracle Day: Escape to LA', url: 'https://m.media-amazon.com/images/M/MV5BMTAxOTQwNjE5NjReQTJeQWpwZ15BbWU4MDEyMTE2MjIx._V1_.jpg' },
  S04E05: { imdbEpisodeId: 'tt1819344', imdbTitle: 'Miracle Day: The Categories of Life', url: 'https://m.media-amazon.com/images/M/MV5BMjA3Njk0ODgyNl5BMl5BanBnXkFtZTgwMjYxMTYyMjE@._V1_.jpg' },
  S04E06: { imdbEpisodeId: 'tt1819348', imdbTitle: 'Miracle Day: The Middle Men', url: 'https://m.media-amazon.com/images/M/MV5BMTU0NjY1NDI2MF5BMl5BanBnXkFtZTgwNzUxMTYyMjE@._V1_.jpg' },
  S04E07: { imdbEpisodeId: 'tt1819347', imdbTitle: 'Miracle Day: Immortal Sins', url: 'https://m.media-amazon.com/images/M/MV5BMTY5MTYwNDIxNV5BMl5BanBnXkFtZTgwNTExMTYyMjE@._V1_.jpg' },
  S04E08: { imdbEpisodeId: 'tt1819343', imdbTitle: 'Miracle Day: End of the Road', url: 'https://m.media-amazon.com/images/M/MV5BMTczNjk5ODk4N15BMl5BanBnXkFtZTgwOTIxMTYyMjE@._V1_.jpg' },
  S04E09: { imdbEpisodeId: 'tt1819346', imdbTitle: 'Miracle Day: The Gathering', url: 'https://m.media-amazon.com/images/M/MV5BMjEyNjUyOTk2OV5BMl5BanBnXkFtZTgwMTQxMTYyMjE@._V1_.jpg' },
  S04E10: { imdbEpisodeId: 'tt1819349', imdbTitle: 'Miracle Day: The Blood Line', url: 'https://m.media-amazon.com/images/M/MV5BNDUxNTM0NjQ0NV5BMl5BanBnXkFtZTgwNDIxMTYyMjE@._V1_.jpg' }
};

module.exports = Object.freeze(episodeImages);
